# Generated by Django 2.2.2 on 2019-07-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trombi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_person_friends_+', to='trombi.Person'),
        ),
    ]
